# Generated by Django 3.1.1 on 2021-07-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210723_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approve_comment',
        ),
    ]
