# Generated by Django 3.1.1 on 2021-10-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0008_auto_20210728_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestsend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_confirmed', models.BooleanField(default=False)),
                ('sendby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendby', to=settings.AUTH_USER_MODEL)),
                ('sendto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sendby', 'sendto')},
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('following', 'followers')},
            },
        ),
    ]
